### ISSUE TITLE
Issues in fisher score computation

### ISSUE THREAD

**Issue by ajeetkverma** [DengZeshuai/SRTTA#4]
I have used all the deafault settings, getting stucked at this point:

[24/07/20 16:16:14] [srtta.py:  123]: use GaussianBlur for im_5
Traceback (most recent call last):
  File "C:\Users\akver\Desktop\VSR\SRTTA\src\main_tta.py", line 287, in <module>
    main(args)
  File "C:\Users\akver\Desktop\VSR\SRTTA\src\main_tta.py", line 186, in main
    img_out = srtta_model(train_loader, img_lr, img_gt, filename[0], corruption)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\akver\Desktop\VSR\SRTTA\src\srtta.py", line 125, in __call__
    self.test_time_adaptation(train_loader, corruptions)
  File "C:\Users\akver\Desktop\VSR\SRTTA\src\srtta.py", line 187, in test_time_adaptation
    self.fisher_restoration()
  File "C:\Users\akver\Desktop\VSR\SRTTA\src\srtta.py", line 217, in fisher_restoration
    mask = self.fishers[f"{nm}.{npp}"][-1]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'body.0.body.0.weight'

**Comment by Caesarhhh** [comment]
It seems that the function compute_fisher has not been executed. Please debug and check if the function is executing normally.

**Comment by ajeetkverma** [comment]
solved it by commenting line  in srtta.py
```
if t_data.dataset.name != "Set5": continue
```

i found this line was making code to skip the fishers metric, and causing the issues.

Thank you for prompt reply.
